### ISSUE TITLE
Can we use the MongoDB as default scheduler store.

### ISSUE THREAD

**Issue by harshalizode** [dymmond/asyncz#58]
Hello,
I want to use the mongoDB as scheduler store. But adding the configuration of scheduler it raising exceptions.
To configure the scheduler I am doing same as mentioned in the Asyncz documentation.

Issue as:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/proj.env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/playmity/main.py", line 19, in <module>
    from playmity.startup_scripts import load_permissions, \
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/playmity/startup_scripts.py", line 17, in <module>
    from common.decorator import require_application_models
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/common/decorator.py", line 17, in <module>
    logger = settings.logger
  File "/home/proj.env/lib/python3.10/site-packages/esmerald/utils/functional.py", line 12, in inner
    self._setup()
  File "/home/proj.env/lib/python3.10/site-packages/esmerald/conf/__init__.py", line 40, in _setup
    settings: Type["EsmeraldAPISettings"] = reload_settings()
  File "/home/proj.env/lib/python3.10/site-packages/esmerald/conf/__init__.py", line 23, in reload_settings
    settings: Type["EsmeraldAPISettings"] = import_string(settings_module)
  File "/home/proj.env/lib/python3.10/site-packages/lilya/_internal/_module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/playmity/configs/development/__init__.py", line 5, in <module>
    from .settings import DevelopmentAppSettings
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/playmity/configs/development/settings.py", line 54, in <module>
    class DevelopmentAppSettings(AppSettings):
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/playmity/configs/development/settings.py", line 173, in DevelopmentAppSettings
    scheduler: AsyncIOScheduler = AsyncIOScheduler(
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/asyncio.py", line 24, in __init__
    super().__init__(**kwargs)
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/base.py", line 103, in __init__
    self.setup(self.global_config, **kwargs)
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/base.py", line 152, in setup
    self._setup(config)
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/asyncio.py", line 40, in _setup
    super()._setup(config)
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/base.py", line 721, in _setup
    self.add_store(value, alias)
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/base.py", line 320, in add_store
    self.wakeup()
  File "/home/proj.env/lib/python3.10/site-packages/asyncz/schedulers/utils.py", line 13, in wrapper
    self.event_loop.call_soon_threadsafe(wrapped)
AttributeError: 'NoneType' object has no attribute 'call_soon_threadsafe'
```
Thank you.

**Comment by tarsil** [comment]
Perfect, I will have a look and come back to you @harshalizode

**Comment by tarsil** [comment]
@harshalizode i think I was able to replicate and I can now try to address and hopefully tomorrow we get it done and you are unblocked

**Comment by harshalizode** [comment]
Yes, thank you.

**Comment by tarsil** [comment]
@harshalizode can you show me an example here how are you trying to run the config, please? I thought I was able to replicate but apparently I was wrong.

**Comment by harshalizode** [comment]
Yes sure, I have configured the scheduler as follow.

```
# main.py
app = Esmerald(
        routes=[Include(namespace="scheduler_example.urls")],
        enable_scheduler=True,
        scheduler_class=AsyncIOScheduler(
        {
            "asyncz.stores.mongo": {"type": "mongodb"},
            "asyncz.stores.default": {"type": "redis", "database": "0"},
            "asyncz.executors.threadpool": {
                "max_workers": "20",
                "class": "asyncz.executors.threadpool:ThreadPoolExecutor",
            },
            "asyncz.executors.default": {"class": "asyncz.executors.asyncio::AsyncIOExecutor"},
            "asyncz.task_defaults.coalesce": "false",
            "asyncz.task_defaults.max_instances": "3",
            "asyncz.task_defaults.timezone": "UTC",
        },
    )
        scheduler_tasks={
            "collect_market_data": "scheduler_example.apps.accounts.tasks",
            "send_newsletter": "scheduler_example.apps.accounts.tasks",
            "scheduler_demo": "scheduler_example.apps.accounts.tasks",
        },
        on_startup=[do_startup]
    )
    return app
```

Scheduler as:

```
# Scheduler
from asyncz.contrib.esmerald.decorator import scheduler
from asyncz.triggers import IntervalTrigger
from esmerald.conf import settings

logger = settings.logger
count = 0


@scheduler(
    name="print_no_of_running_count",
    trigger=IntervalTrigger(seconds=10),
    max_instances=3,
    store="mongo",
    executor="default",
)
def scheduler_demo():
    global count
    count += 1
    print(f"Scheduler running count {count}")
```
If we move the scheduler_class from the app instance then we can't use the store as "mongo" in the scheduler decorator.

**Comment by tarsil** [comment]
Yap go it. I've found some typos that will be updated in the new release as well

**Comment by harshalizode** [comment]
Okay, thank you.

**Comment by tarsil** [comment]
@harshalizode a new release was done now and some internal fixes were added. Please install `asyncz>=0.8.0`. Pin that in your requirements, although in the future when you install `esmerald[schedulers]` it should pull automatically the latest version but just in case for now do the asyncz installation. 

For your config, a minor change to:

```python
# main.py
app = Esmerald(
        routes=[Include(namespace="scheduler_example.urls")],
        enable_scheduler=True,
        scheduler_class=AsyncIOScheduler(
        {
            "asyncz.stores.mongo": {"type": "mongodb"},
            "asyncz.stores.default": {"type": "redis", "database": "0"},
            "asyncz.executors.threadpool": {
                "max_workers": "20",
                "class": "asyncz.executors.threadpool:ThreadPoolExecutor",
            },
            "asyncz.executors.default": {"class": "asyncz.executors.asyncio:AsyncIOExecutor"},
            "asyncz.task_defaults.coalesce": "false",
            "asyncz.task_defaults.max_instances": "3",
            "asyncz.task_defaults.timezone": "UTC",
        },
    )
        scheduler_tasks={
            "collect_market_data": "scheduler_example.apps.accounts.tasks",
            "send_newsletter": "scheduler_example.apps.accounts.tasks",
            "scheduler_demo": "scheduler_example.apps.accounts.tasks",
        },
        on_startup=[do_startup]
    )
    return app
```

You can do like this or you can do in another way.

```python
# main.py
app = Esmerald(
        routes=[Include(namespace="scheduler_example.urls")],
        enable_scheduler=True,
        scheduler_configurations={
            "asyncz.stores.mongo": {"type": "mongodb"},
            "asyncz.stores.default": {"type": "redis", "database": "0"},
            "asyncz.executors.threadpool": {
                "max_workers": "20",
                "class": "asyncz.executors.threadpool:ThreadPoolExecutor",
            },
            "asyncz.executors.default": {"class": "asyncz.executors.asyncio:AsyncIOExecutor"},
            "asyncz.task_defaults.coalesce": "false",
            "asyncz.task_defaults.max_instances": "3",
            "asyncz.task_defaults.timezone": "UTC",
        },
        scheduler_tasks={
            "collect_market_data": "scheduler_example.apps.accounts.tasks",
            "send_newsletter": "scheduler_example.apps.accounts.tasks",
            "scheduler_demo": "scheduler_example.apps.accounts.tasks",
        },
        on_startup=[do_startup]
    )
    return app
```

Up to you. I'm changing here directly, so if there is any missing comma, just make sure you have the right syntax :).

**Comment by tarsil** [comment]
There is also the example I gave you in the [docs](https://asyncz.tarsild.io/contrib/esmerald/scheduler/)

**Comment by harshalizode** [comment]
Good morning,
I think something is missed by resolving the issue I still getting the error while runing the scheduler with same configuration that you have provided.
```

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 78, in subprocess_started
    target(sockets=sockets)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/config.py", line 433, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/harshaliz/Desktop/proj/main.py", line 22, in <module>
    from playmity.startup_scripts import load_permissions, \
  File "/home/harshaliz/Desktop/proj/startup_scripts.py", line 17, in <module>
    from common.decorator import require_application_models
  File "/home/harshaliz/Desktop/Projects/Playmity/trunk/playmity_be/common/decorator.py", line 17, in <module>
    logger = settings.logger
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/esmerald/utils/functional.py", line 12, in inner
    self._setup()
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/esmerald/conf/__init__.py", line 31, in _setup
    settings: Type["EsmeraldAPISettings"] = import_string(settings_module)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/lilya/_internal/_module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/harshaliz/Desktop/proj/configs/development/__init__.py", line 5, in <module>
    from .settings import DevelopmentAppSettings
  File "/home/harshaliz/Desktop/proj/configs/development/settings.py", line 55, in <module>
    class DevelopmentAppSettings(AppSettings):
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 183, in __new__
    complete_model_class(
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 550, in complete_model_class
    generate_pydantic_signature(init=cls.__init__, fields=cls.model_fields, config_wrapper=config_wrapper),
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/_internal/_signature.py", line 159, in generate_pydantic_signature
    merged_params = _generate_signature_parameters(init, fields, config_wrapper)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/_internal/_signature.py", line 115, in _generate_signature_parameters
    kwargs = {} if field.is_required() else {'default': field.get_default(call_default_factory=False)}
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/fields.py", line 507, in get_default
    return _utils.smart_deepcopy(self.default)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/_internal/_utils.py", line 318, in smart_deepcopy
    return deepcopy(obj)  # slowest way when we actually might need a deepcopy
  File "/usr/lib/python3.10/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/home/harshaliz/proj.env/lib/python3.10/site-packages/pydantic/main.py", line 717, in __deepcopy__
    _object_setattr(m, '__dict__', deepcopy(self.__dict__, memo=memo))
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 265, in _reconstruct
    y = func(*args)
  File "/usr/lib/python3.10/copy.py", line 264, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.10/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 211, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 211, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.10/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.10/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.10/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle '_contextvars.Context' object
Exception ignored in: <function BaseEventLoop.__del__ at 0x7b01cc1284c0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 687, in __del__
    if not self.is_closed():
  File "/usr/lib/python3.10/asyncio/base_events.py", line 684, in is_closed
    return self._closed
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_closed'

```

Check the traceback.

**Comment by tarsil** [comment]
@harshalizode yes, I think the example was updated before. It's not "threadpool:ThreadPoolExecutor". Replace to "pool:ThreadPoolExecutor"

**Comment by tarsil** [comment]
Let me also run a quick update there as I think we also have an internal typo. I will come back to you soon

**Comment by tarsil** [comment]
Although a version 0.8.1 was released for an internal mapping this example https://asyncz.tarsild.io/schedulers/#second-option tells what I meant

**Comment by harshalizode** [comment]
Still having the same issue, is it resolved?

**Comment by tarsil** [comment]
Version 0.8.1 has a fix there but did you see the example of the link I sent you? It's literally the same as the tests provided in Asyncz https://github.com/dymmond/asyncz/blob/main/tests/contrib/esmerald/test_esmerald_config.py

**Comment by tarsil** [comment]
@harshalizode that is coming next release as we want to change the way we pass the configurations of Asyncz. Instead of all parameters, we will pass a `AsynczConfig` object that will contain all the configurations needed for asyncz. As of now, not yet.

**Comment by tarsil** [comment]
Ok, but I do need to see the way you declared the task, please

**Comment by harshalizode** [comment]
Yes, sure.
```
app = Esmerald(
        routes=[
            Gateway(handler=languages),
            Gateway(handler=verify_reg_token),
            Gateway(handler=reset_password),
            Gateway(handler=forgot_password),
            Gateway(handler=userlogin),
            Include(
                routes=[Include(namespace="proj.urls")],
            ),
        ],
        enable_scheduler=True,
        scheduler_tasks={
            "scheduler_demo": "proj.apps.common.tasks"
        },
        scheduler_configurations={
            "asyncz.stores.default": {"type": "mongodb", "client": MongoClient(
              settings.mongo_database_uri, connect=False, authSource="admin")},
            # "asyncz.stores.default": {"type": "redis", "database": "0"},
            "asyncz.executors.pool": {
                "max_workers": "20",
                "class": "asyncz.executors.pool:ThreadPoolExecutor",
            },
            "asyncz.executors.default": {"class": "asyncz.executors.asyncio:AsyncIOExecutor"},
            "asyncz.task_defaults.coalesce": "false",
            "asyncz.task_defaults.max_instances": "3",
            "asyncz.task_defaults.timezone": "UTC",
        },
        # Load the default permission and version controlling mechanism
        on_startup=[load_permissions],
        interceptors=[RequestParamInterceptor],
        dependencies={
            "logger": Inject(logger_injection),
        },
        exception_handlers={
                    HTTPException: custom_http_exception_handler}
                )
    return app
```

**Comment by tarsil** [comment]
Let me have a look

**Comment by harshalizode** [comment]
Hello,
Any update?

**Comment by tarsil** [comment]
@harshalizode will look as soon as possible. Unfortunately we all work 100% + maintaining this. You should know this soon

**Comment by harshalizode** [comment]
Okay, thank you.

**Comment by harshalizode** [comment]
@tarsil you have released the version for it?

**Comment by tarsil** [comment]
@harshalizode closed the wrong one

**Comment by harshalizode** [comment]
Okay.

**Comment by tarsil** [comment]
@harshalizode please install the version 0.8.2. It was a missing default in the internal setup and typing clash.

**Comment by tarsil** [comment]
Let me know if its addressed. Esmerald support will be updated in the next release but that will require some time.

**Comment by tarsil** [comment]
@harshalizode ?

**Comment by harshalizode** [comment]
Okay, I will check once and let you know.
Thank you :-)

**Comment by harshalizode** [comment]
Hello,
 I have configured scheduler as:
```
def get_scheduler_config() -> AsynczConfig:
    """
    Builds the scheduler configuration.
    """
    return AsynczConfig(
        stores={"default": MongoDBStore(client=MongoClient(
            mongo_database_uri, connect=False, authSource="admin"))},
        tasks={
            "collect_market_data": "accounts.tasks",
            "send_newsletter": "accounts.tasks",
            "scheduler_demo": "accounts.tasks",
        }
    )
```
 and the tasks as:

```
import logging
from loguru import logger

from asyncz.triggers import IntervalTrigger
from esmerald.contrib.schedulers.asyncz.decorator import scheduler

logging.basicConfig()
logging.getLogger("esmerald").setLevel(logging.DEBUG)

@scheduler(name="collect_data",
           trigger=IntervalTrigger(seconds=1),
           max_instances=3)
def collect_market_data():
    logger.error("Collecting market data")
    ...


@scheduler(
    name="send_email_newsletter",
    trigger=IntervalTrigger(seconds=3),
    max_instances=3,
)
def send_newsletter():
    logger.warning("sending email newsletter!")
    ...

count = 0

@scheduler(
    name="scheduler_demo",
    trigger=IntervalTrigger(seconds=10),
    max_instances=3,
)
def scheduler_demo():
    global count
    count += 1
    print(f"Scheduler running count {count}")

```
Check the console:

![scheduler_op](https://github.com/dymmond/asyncz/assets/66934194/54876238-86d0-446a-8b3e-440e9fdfe9e3)

It shouldn't have logged the messages? also does not receive the debug point.

**Comment by harshalizode** [comment]
Hello,
Is the issue reproduced at the end?

**Comment by tarsil** [comment]
I'm not having this issue. It's quite hard to reproduce. Don't use print. Use the logger to see it as well. So far I'm not able to reproduce it

**Comment by harshalizode** [comment]
Logger messages is also not get logged.

**Comment by tarsil** [comment]
@harshalizode this might be related with any configuration of the logger that might need some tweaking on your side. I will try to have a look later and see what I can do to help you

**Comment by harshalizode** [comment]
I have ran the provided repo code only 
https://github.com/dymmond/scheduler-example

**Comment by tarsil** [comment]
@harshalizode I didn't change too much your example, actually its the same but running faster (internal)

![image](https://github.com/dymmond/asyncz/assets/11027931/ed5cd1f7-0c07-4cfa-8534-571b8dc5f2bc)

I have updated the https://github.com/dymmond/scheduler-example as well, again, containing also the task for the count. It works

**Comment by harshalizode** [comment]
@tarsil you used the default store memory; with memory, everything works perfectly.
However, when I change the default storage to MongoDB, everything works as before.

I have configured the scheduler config as:
```
def get_scheduler_config() -> AsynczConfig:
    """
    Builds the scheduler configuration.
    """
    return AsynczConfig(
        stores={"default": MongoDBStore(client=MongoClient(
            mongo_database_uri, connect=False, authSource="admin"))},
        tasks={
            "collect_market_data": "accounts.tasks",
            "send_newsletter": "accounts.tasks",
            "scheduler_demo": "accounts.tasks",
        }
    )
```

**Comment by harshalizode** [comment]
Hello @tarsil, is the issue reproduced at the end?

**Comment by tarsil** [comment]
@harshalizode i was able to reproduce it yes

**Comment by harshalizode** [comment]
Okay, what was the root cause for it?

**Comment by tarsil** [comment]
Still under investigation but I should know soon

**Comment by harshalizode** [comment]
Okay.

**Comment by tarsil** [comment]
@harshalizode there was an internal reference not being checked as asyncz was not considering possible implementations done by a decorator implementing the `fn` from the task.

You can install asyncz 0.8.3 and its working. I updated the example repo to also run with a mongo store and its working 

![image](https://github.com/dymmond/asyncz/assets/11027931/574a9a4e-931f-4fe8-8924-ffe370ebb674)

Btw this was not actually a bug from asyncz itself but since Esmerald creates a wrapper for it, asyncz is now also covering them. Nice catch but now everything should work like a charm

**Comment by harshalizode** [comment]
Yes , Its working like a charm now :-)

**Comment by tarsil** [comment]
Perfect 🙂

**Comment by harshalizode** [comment]
What is storing in the status as BindData in the MongoDB?

**Comment by tarsil** [comment]
A task object

**Comment by harshalizode** [comment]
How can we know it will succeed or failure task?
we have the record as:
```
{
    _id: '88a7d98995434c11942a44299e9dd948',
    next_run_time: 1718858784.637183,
    state: BinData(0, 'gAWVCAMAAAAAAACMFWFzeW5jei5kYXRhc3RydWN0dXJlc5SMCVRhc2tTdGF0ZZSTlCmBlH2UKIwIX19kaWN0X1+UfZQojAJpZJSMIDg4YTdkOTg5OTU0MzRjMTE5NDJhNDQyOTllOWRkOTQ4lIwEbmFtZZSMDGNvbGxlY3RfZGF0YZSMAmZulIwiYWNjb3VudHMudGFza3M6Y29sbGVjdF9tYXJrZXRfZGF0YZSMDGZuX3JlZmVyZW5jZZRoDIwEYXJnc5QpjAZrd2FyZ3OUfZSMCGNvYWxlc2NllIiMB3RyaWdnZXKUjBhhc3luY3oudHJpZ2dlcnMuaW50ZXJ2YWyUjA9JbnRlcnZhbFRyaWdnZXKUk5QpgZRoAIwNSW50ZXJ2YWxTdGF0ZZSTlCmBlH2UKGgFfZQojAh0aW1lem9uZZSMCGJ1aWx0aW5zlIwHZ2V0YXR0cpSTlIwIem9uZWluZm+UjAhab25lSW5mb5STlIwJX3VucGlja2xllIaUUpSMDEFzaWEvS29sa2F0YZRLAYaUUpSMCHN0YXJ0X2F0lIwIZGF0ZXRpbWWUjAhkYXRldGltZZSTlEMKB+gGEwkjBQm4/5RoKIaUUpSMBmVuZF9hdJROjAhpbnRlcnZhbJRoKowJdGltZWRlbHRhlJOUSwBLAUsAh5RSlIwGaml0dGVylE51jBJfX3B5ZGFudGljX2V4dHJhX1+UTowXX19weWRhbnRpY19maWVsZHNfc2V0X1+Uj5QoaDFoHGgwaDZoKZCMFF9fcHlkYW50aWNfcHJpdmF0ZV9flE51YmKMCGV4ZWN1dG9ylIwHZGVmYXVsdJSMFW1pc3RyaWdnZXJfZ3JhY2VfdGltZZRLAYwNbWF4X2luc3RhbmNlc5RLAYwNbmV4dF9ydW5fdGltZZRoLEMKB+gGFAoQGAm4/5RoKIaUUpSMCXNjaGVkdWxlcpROjAtzdG9yZV9hbGlhc5ROjAVzdG9yZZROdWg3Tmg4j5QoaAdoDWgJaAtoPWg+aA5oO2gSaD9oEWgPkGg6TnViLg==')
}
```
Here, we have the two values in the BindData object, second one representing the task object and the first one?
One more doubt is we can store the additional data into the task results?

**Comment by tarsil** [comment]
@harshalizode im not following your questions. This is for internal management of the asyncz tasks. You should not worry about it, Asyncz takes care of those states.

What additional data? The task I'm referring is not the task that you are using in Esmerald, it's an internal Asyncz object that we call also task, in the past we called it job

**Comment by tarsil** [comment]
Now, if you want additional fields to the current task object, you can extend it and add them and then use it.

**Comment by harshalizode** [comment]
Okay, the concern only is if we want to show the task details with there status if they failed or successes.
